services:
  - type: web
    name: url-shortener
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install && cd ../client && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
